Feature/login screen
Davi-s-Brain/Onboarding-instituto-front pull request #6
Opened 2022-02-24 18:38 UTC by Davi-s-Brain

Tela de login de front
Sem verificação por enquanto, apenas no próximo passo

2022-02-24 21:39 UTC, dan-ueno commented on src/App.test.tsx
> +  render(<Login />);
não precisa rodar os testes no front haha, pode deixar esse arquivo de lado

2022-02-24 22:12 UTC, dan-ueno commented on src/components/Login.component.tsx
> +      <Input type='Email' />
no type email é minusculo, ficou ok com ele assim?

2022-02-24 22:12 UTC, dan-ueno commented on src/components/Login.component.tsx
> +export default function Login():JSX.Element {
a gente não usa export default, e no geral as funções são consts

2022-02-24 22:13 UTC, dan-ueno commented on src/index.tsx
> +    <Login />
aqui o certo é o estar o App mesmo, pq precisa seguir index --> App --> coisas do app (no seu caso, so vai ter Login dentro do App)

2022-02-24 22:13 UTC, dan-ueno requested changes
a parte de como a rota ta feita pra chegar no login ta errado

2022-02-25 12:11 UTC, Davi-s-Brain commented on src/App.test.tsx
> +  render(<Login />);
Certo

2022-02-25 12:11 UTC, Davi-s-Brain commented on src/components/Login.component.tsx
> +      <Input type='Email' />
Eu troquei de qualquer forma

2022-02-25 12:14 UTC, Davi-s-Brain commented on src/index.tsx
> +    <Login />
hmm entendi

2022-02-25 13:58 UTC, Davi-s-Brain commented
> a parte de como a rota ta feita pra chegar no login ta errado

Eu corrigi isso no próximo PR que ainda vou abrir, daí eu faço o merge desse e lido com o conflito depois.

2022-02-28 13:14 UTC, dan-ueno approved these changes

2022-02-28 14:31 UTC, merged